services:
  vrising:
    image: sknnr/vrising-dedicated-server:latest
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
    environment:
      - SERVER_NAME="VRising Containerized"
      - SERVER_PASSWORD="PleaseChangeMe"
      - GAME_PORT=27015
      - QUERY_PORT=27016
      - DESCRIPTION="A VRising Server"
      - BIND_ADDRESS=0.0.0.0
      - HIDE_IP=true
      - LOWER_FPS_EMPTY=true
      - SECURE=true
      - EOS_LIST=true
      - STEAM_LIST=false
      - GAME_PRESET=StandardPvP
      - DIFFICULTY=Difficulty_Normal
      - SAVE_NAME=vrising_world
    volumes:
      - vrising-persistent-data:/opt/steam/vrising/save-data
volumes:
  vrising-persistent-data:
